all:
	g++ -lfftw3 fft_test.cpp -o fft_test.o
	g++ -lfftw3 transpose_test.cpp -o transpose_test.o
	g++ -lfftw3 array_test_2.cpp -o array_test.o
	#g++ -lfftw3 fft3d_test.cpp -o test3d.o
	g++ -lfftw3 symmetrize_r_test.cpp -o s.o
clean:
	rm *.o
	rm *.txt
